language: elixir
elixir:
  - 1.10.4
  - 1.11.2
otp_release:
  - 21.0
  - 22.0
  - 23.0

cache:
  directories:
  - deps
  - _build

env:
  global:
    - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  # Check that code is formatted
  - "mix format --dry-run --check-formatted"
  # Run all tests except pending ones
  - "mix test --trace"

# TODO: Put it off till later. I need to write better documentation before
# jobs:
#   include:
#     - stage: code_coverage
#       script:
#         - "mix deps.get"
#         # Push code coverage
#         - "mix coveralls.travis"
#       elixir: 1.9.1
#       otp_release: 22.0
